#!/bin/bash
#####################################################################################################
# liuyx@nationalchip.com
# Copyright (C), 2013-2020, HangZhou NationalChip Sceince and Technology Corp.
# Parse .config file, generate config header/source file, copy resource needed
#####################################################################################################
if [ -e .config ];then
	source .config
else
	echo "Cannot find .config file, please config first"
	echo "make menuocnfig"
	exit 1
fi

#####################################################################################################
# Set some important variable by manual
CONFIG_BUILD_DIR=$(pwd)
CONFIG_FILE_H=${CONFIG_BUILD_DIR}/include/autogenerated_config.h
#
###################################### copy resource ################################################
# do something

#####################################################################################################

#build config file .h and .c
##.h
echo "#ifndef __AUTOGENERATED_CONFIG_H__" >$CONFIG_FILE_H
echo "#define __AUTOGENERATED_CONFIG_H__">>$CONFIG_FILE_H
echo "/*">>$CONFIG_FILE_H
echo " * DO NOT MODIFY.">>$CONFIG_FILE_H
echo " *">>$CONFIG_FILE_H
echo " * This file was generated by Makefile">>$CONFIG_FILE_H
echo " *">>$CONFIG_FILE_H
echo " */">>$CONFIG_FILE_H
echo "">>$CONFIG_FILE_H

sed 's/^#\(.*\)=.*/# \1  is not set/g' .config\
    |sed 's/^#/\/\//g'\
    |sed 's/\(.*\)="\(.*\)"/\1=\2/g'\
    |sed 's/^CONFIG_\(.*\)=y/#define \1/g'\
    |sed 's/^CONFIG_\(.*\)=\(.*\)/#define \1 \2/g' | grep -E "SYS_SOC | SYS_VENDOR | SYS_BOARD" >> $CONFIG_FILE_H


echo "">>$CONFIG_FILE_H
echo "#endif">>$CONFIG_FILE_H
#cat $(CONFIG_FILE_H)
